# Generated by Django 2.1.1 on 2018-09-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
                ('reward', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('tel', models.CharField(max_length=11)),
                ('count', models.IntegerField(default=0)),
                ('is_top', models.BooleanField(default=False)),
                ('is_flush', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'publish',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_select', models.BooleanField(default=False)),
                ('submit_date', models.DateTimeField(auto_now=True)),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Publish')),
            ],
            options={
                'db_table': 'reply',
                'ordering': ['-submit_date'],
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.IntegerField(default=0)),
                ('home', models.IntegerField(default=0)),
                ('market', models.IntegerField(default=0)),
                ('find', models.IntegerField(default=0)),
                ('connect', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sort',
            },
        ),
        migrations.CreateModel(
            name='Sure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pub_sure', models.BooleanField(default=False)),
                ('is_rep_sure', models.BooleanField(default=False)),
                ('pub_comment', models.CharField(max_length=280)),
                ('rep_comment', models.CharField(max_length=280)),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Publish')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Reply')),
            ],
            options={
                'db_table': 'sure',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
                ('tel', models.CharField(max_length=11)),
                ('qq', models.CharField(max_length=11)),
                ('wechat', models.CharField(max_length=20)),
                ('gold', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('collect', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='publish',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='publish',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Sort'),
        ),
    ]
