# Generated by Django 2.1 on 2018-09-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180903_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(default='110', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(default='110', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat',
            field=models.CharField(default='110', max_length=20),
        ),
    ]
